model: ResNetSE34V2
log_input: True
encoder_type: ASP
trainfunc: softmaxproto
trainfunc_dev: softmax
nPerSpeaker: 2
multi_task: False
nOut: 512
batch_size: 16
scale: 15
margin: 0.3
n_mels: 64
test_interval: 3
max_frames: 800
eval_frames: 0
weight_decay: 0.00005
lr: 0.001
lr_decay: 0.95
augment: False
initial_model: /content/drive/MyDrive/VLSP2022/exps/ResNet34V2_pretrained/model/baseline_v2_smproto.model
save_path: /content/drive/MyDrive/VLSP2022/exps/ResNet34V2_pretrained_8s_softmaxproto
train_list: /content/drive/MyDrive/VLSP2022/extracted_dataset/I-MSV-DATA/Dev_Enr_10s_data.csv
train_path: /content/drive/MyDrive/VLSP2022/extracted_dataset/I-MSV-DATA
test_list: /content/drive/MyDrive/VLSP2022/extracted_dataset/I-MSV-DATA/eval_sessionB.csv
